### PR TITLE
errorfix graphql.py about warning NotFoundKey

### PR DESCRIPTION
**Pull request by TheGreatestNyanCat**
see issue : https://github.com/fa0311/TwitterInternalAPIDocument/issues/391

### CODE REVIEW

**Review by fa0311 — COMMENTED** [review]
Can you erase lines 127, 129, 136, 142 ?
Otherwise it looks good to me.

**Comment by TheGreatestNyanCat** [comment]
Ok. I try that

**Comment by fa0311** [comment]
Delete line 127 and change line 130 to else if to reduce indentation :)

**Comment by TheGreatestNyanCat** [comment]
@fa0311 check now.

**Comment by TheGreatestNyanCat** [comment]
now fixed. check now.

**Comment by fa0311** [comment]
> Delete line 127 and change line 128 to elif to reduce indentation

This was my mistake.
Can you restore 1284902?

**Comment by TheGreatestNyanCat** [comment]
now fixed.

**Review by fa0311 — APPROVED** [review]
It looks good to me!
Thanks for taking the time to work on this project!

**Pull request merged**
